"""add device info

Revision ID: b67ec5f0d5b5
Revises: fbc0901d0f58
Create Date: 2026-02-15 14:00:22.043789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b67ec5f0d5b5'
down_revision: Union[str, Sequence[str], None] = 'fbc0901d0f58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calculation_logs', sa.Column('device_info', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('calculation_logs', 'device_info')
    # ### end Alembic commands ###
